[package]
name = "physical_constants"
version = "0.1.0"
description = "CODATA recommended values of physical constants"
repository = "https://github.com/JonasOlson/rust-physical_constants"
keywords = ["physics", "constants", "CODATA"]
license = "GPL-3.0"
authors = ["Jonas Olson <jolson@kth.se>"]
build = "build.rs"
